spring.application.name=NewsPortalApp

spring.datasource.url=jdbc:postgresql://localhost:5432/news_portal
spring.datasource.username=postgres
spring.datasource.password=tuku1234

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=86400000

cloudinary.cloud-name=diuaqzygu
cloudinary.api-key=758434389477635
cloudinary.api-secret=vRpPgMnmlBdDR7o6l-06zjTP0bI


